# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master


stages:
- stage: Tests
  jobs:

  - job: unittest
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'unittest'
    steps:
    - script: |
        apt update
        # gcc needed for building mysql pip package
        apt install -y gcc
        apt install -y python3
        apt install -y python3-pip
        apt install -y libmysqlclient-dev
        apt install -y python-dev-is-python3
        apt install -y mysql-client
        apt install -y libmysqlclient21
        # ...
        python -m pip install -r requirements.txt
        python -m unittest

  - job: pylint
    pool:
      vmImage: 'windows-2019'
    displayName: 'pylint'
    steps:
    - script: |
        install.bat
        venv\Scripts\python.exe -m pip install pylint
        venv\Scripts\python.exe -m pylint *.py

